<?php
/** Fraction Calculator — English (United States). UI strings, step templates, FAQ. */
return [
    'title'   => 'Fraction Calculator With Steps — Add, Subtract, Multiply & Divide',
    'meta'    => 'Free fraction calculator with steps: add, subtract, multiply and divide fractions and mixed numbers, simplify, convert fractions to decimals and percents, compare and order fractions.',
    'h1'      => 'Fraction Calculator',
    'kicker'  => 'Fractions calculator with steps',
    'intro'   => 'Add, subtract, multiply and divide fractions, mixed numbers and whole numbers. Every answer is exact, simplified and explained step by step — plus tools to simplify, convert to decimals and percents, compare, order and find a fraction of a number.',
    'badges'  => ['Exact answers', 'Step-by-step', 'Mixed numbers', 'Free, no sign-up'],
    'crumbHome' => 'Home',
    'faqTitle'  => 'Frequently asked questions',
    'relatedTitle' => 'More calculators',
    'privacy' => 'Every calculation runs in your browser. No account is needed and the fractions you type are not sent to a server or stored.',
    'related' => [
        'garage-sale-pricing-calculator' => ['Garage Sale Pricing Calculator', 'Prices for used items, rounded to easy amounts.'],
        'date-of-birth-calculator'       => ['Date of Birth Calculator', 'Exact age in years, months and days.'],
    ],

    'ui' => [
        'calculator' => 'Calculator', 'modes' => 'Calculator modes', 'skip' => 'Skip to calculator', 'language' => 'Language',
        'theme' => 'Toggle dark or light theme', 'footer' => 'Calculations run locally in your browser.', 'otherLang' => 'This calculator in another language',
        'm_calc' => 'Fraction Calculator', 'm_multi' => 'Multiple Fractions', 'm_simplify' => 'Simplify', 'm_mixed' => 'Mixed Numbers',
        'm_decimal' => 'Decimal', 'm_percent' => 'Percent', 'm_compare' => 'Compare', 'm_order' => 'Order',
        'm_of' => 'Fraction of a Number', 'm_what' => 'What Fraction Is X of Y?', 'm_equiv' => 'Equivalent Fractions',
        'whole' => 'whole number', 'num' => 'numerator', 'den' => 'denominator', 'wholeShort' => 'whole', 'numShort' => 'top', 'denShort' => 'bottom',
        'fracA' => 'First fraction', 'fracB' => 'Second fraction', 'fraction' => 'Fraction', 'fractionN' => 'Fraction {i}',
        'operation' => 'Operation', 'opAdd' => 'add', 'opSub' => 'subtract', 'opMul' => 'multiply', 'opDiv' => 'divide',
        'calculate' => 'Calculate', 'reset' => 'Reset', 'addRow' => 'Add fraction', 'removeRow' => 'Remove this fraction',
        'multiHint' => 'Add up to 10 fractions. Multiplication and division are done before addition and subtraction.',
        'orderHint' => 'Enter 3 to 10 fractions, mixed numbers or whole numbers.',
        'dirToImproper' => 'Mixed → improper', 'dirToMixed' => 'Improper → mixed',
        'dirFracToDec' => 'Fraction → decimal', 'dirDecToFrac' => 'Decimal → fraction',
        'dirFracToPct' => 'Fraction → percent', 'dirPctToFrac' => 'Percent → fraction',
        'decimalInput' => 'Decimal', 'decHint' => 'Exact for finite decimals like 0.125. Write a repeating part in brackets: 0.(3) = 1/3.',
        'percentInput' => 'Percent (%)', 'number' => 'Number', 'ofWord' => 'of', 'xLabel' => 'X (part)', 'yLabel' => 'Y (whole)', 'whatOfWord' => 'is what fraction of',
        'multStart' => 'Start multiplier', 'count' => 'How many', 'digits' => 'Decimal places', 'examples' => 'Try an example',
        'result' => 'Result', 'steps' => 'Step-by-step solution', 'exactFraction' => 'Simplified fraction', 'mixedNumber' => 'Mixed number',
        'decimal' => 'Decimal', 'percent' => 'Percent', 'gcd' => 'GCD', 'lcd' => 'LCD (least common denominator)', 'original' => 'Original fraction',
        'factor' => 'Divided top and bottom by', 'comparison' => 'Comparison', 'asc' => 'Smallest → largest', 'desc' => 'Largest → smallest',
        'equivList' => 'Equivalent fractions', 'repeatingNote' => 'repeats: {p}',
        'cmpLess' => '{a} is smaller than {b}.', 'cmpGreater' => '{a} is larger than {b}.', 'cmpEqual' => '{a} and {b} are equal.',
        'ofExpr' => '{f} of {x}', 'whatExpr' => '{x} out of {y}',
        'copyResult' => 'Copy result', 'copySteps' => 'Copy steps', 'share' => 'Share', 'print' => 'Print', 'copied' => 'Copied to clipboard.',
        'visParts' => '{n} of {d} equal parts shaded', 'visMixed' => '{w} whole and {n} of {d} parts', 'visNeg' => 'Negative value — size shown: {v}', 'visMore' => '+ {k} more whole',
        'exSimplify' => 'Simplify {f}', 'exMixed' => '{f} as a mixed number', 'exDecToFrac' => '{v} to a fraction', 'exToPct' => '{f} to percent',
        'exCompare' => '{a} vs {b}', 'exOf' => '{a} of {x}',

        'e_empty' => 'Enter a fraction first.', 'e_invalid' => 'Use whole numbers only in each box, for example 3 and 4 for 3/4.',
        'e_zero-den' => 'The denominator (bottom number) can’t be 0.', 'e_div-zero' => 'You can’t divide by zero. Change the second fraction.',
        'e_den-empty' => 'Enter a denominator (bottom number).', 'e_num-empty' => 'Enter a numerator (top number).',
        'e_too-long' => 'That number is too long — use at most 30 digits.', 'e_sign-mixed' => 'For a negative mixed number, put the minus sign on the whole number only (−2 1/3).',
        'e_ellipsis' => 'A decimal with “…” isn’t exact. Write the repeating part in brackets, like 0.(3).', 'e_min-rows' => 'You need at least {n} fractions.',
        'e_max-rows' => 'You can use up to {n} fractions.', 'e_y-zero' => 'Y can’t be 0.', 'e_mult' => 'The start multiplier must be a whole number from 1 to 1000.', 'e_op' => 'Choose an operation.',

        'st_toImproper' => 'Change the mixed number {mixed} to an improper fraction: {w} × {d} + {n} = {top}, so it is {to}.',
        'st_sameDen' => 'The denominators are already the same ({d}), so no conversion is needed.',
        'st_lcd' => 'Find the least common denominator of {list}: LCD = {lcd}.',
        'st_convert' => 'Rewrite {from} with the LCD: multiply top and bottom by {k} → {to}.',
        'st_addNum' => 'Add the numerators and keep the denominator: {expr} = {sum}, giving {res}.',
        'st_subNum' => 'Subtract the numerators and keep the denominator: {expr} = {sum}, giving {res}.',
        'st_combine' => 'Combine the numerators over the LCD: {expr} = {sum}, giving {res}.',
        'st_opStep' => 'Multiply/divide first: {a} {op} {b} = {r}.',
        'st_reciprocal' => 'Dividing means multiplying by the reciprocal: flip {from} to {to}.',
        'st_mulNum' => 'Multiply the numerators: {expr} = {r}.',
        'st_mulDen' => 'Multiply the denominators: {expr} = {r}.',
        'st_simplify' => 'Simplify {from}: the GCD is {g}, so divide top and bottom by {g} → {to}.',
        'st_lowest' => '{f} is already in lowest terms.',
        'st_zero' => 'The numerator is 0, so {from} = 0.',
        'st_toMixed' => 'As a mixed number: {from} = {q} remainder {r} over {d} → {to}.',
        'st_euclid' => 'Find the greatest common divisor with Euclid’s algorithm — GCD = {g}:',
        'st_divideBoth' => 'Divide the numerator and denominator by {g}: {n} ÷ {g} = {rn}, {d} ÷ {g} = {rd}.',
        'st_divide' => 'Divide the numerator by the denominator: {n} ÷ {d} = {q} remainder {r}.',
        'st_mixedResult' => 'The quotient is the whole number and the remainder is the new numerator: {res}.',
        'st_decPlaces' => '{dec} has {k} decimal places, so write it over {p10}: {frac}.',
        'st_repeatDec' => '{dec} has {a} non-repeating and {r} repeating digits; written as a fraction that is {frac}.',
        'st_longDiv' => 'Divide the numerator by the denominator: {n} ÷ {d}.',
        'st_terminates' => 'The denominator {d} has no prime factors other than 2 and 5, so the decimal ends.',
        'st_repeats' => 'The denominator {d} has a prime factor other than 2 or 5, so the decimal repeats forever: {period}.',
        'st_over100' => 'Percent means “out of 100”: {p}% = {frac}.',
        'st_times100' => 'Multiply by 100 to get a percent: {f} × 100 = {r}.',
        'st_pctResult' => 'So the answer is {r}%.', 'st_pctApprox' => 'So the answer is {r}% (repeating).',
        'st_cross' => 'Cross-multiply to compare {a} and {b}: {l} and {r}.',
        'st_lcdCompare' => 'Check with the LCD {lcd}: {a} and {b}.',
        'st_less' => 'The first product is smaller, so {a} < {b}.', 'st_greater' => 'The first product is larger, so {a} > {b}.', 'st_equal' => 'The products are equal, so {a} = {b}.',
        'st_orderNums' => 'With a common denominator, order the fractions by their numerators.',
        'st_ofMul' => '“Of” means multiply: {f} × {x} = {expr} = {r}.',
        'st_whatFrac' => 'Write the part over the whole: {x} ÷ {y} = {f}.',
        'st_equivRule' => 'Multiply the numerator and denominator of {f} by the same number to get equivalent fractions.',
    ],

    'faq' => [
        ['What is a fraction calculator?', 'It is a tool that does arithmetic with fractions — adding, subtracting, multiplying and dividing — and gives the answer in simplest form. This one also shows each step, works with mixed numbers and negative fractions, and converts results to decimals and percents.'],
        ['How do you add fractions?', 'Give the fractions a common denominator, add the numerators, keep the denominator and simplify. For 1/2 + 1/3 the least common denominator is 6, so 3/6 + 2/6 = 5/6.'],
        ['How do you subtract fractions?', 'The same way as adding, but subtract the numerators: 3/4 − 1/6 uses the denominator 12, so 9/12 − 2/12 = 7/12.'],
        ['How do you multiply fractions?', 'Multiply the numerators together and the denominators together, then simplify: 2/3 × 3/4 = 6/12 = 1/2. No common denominator is needed.'],
        ['How do you divide fractions?', 'Flip the second fraction (use its reciprocal) and multiply: 2/3 ÷ 4/5 = 2/3 × 5/4 = 10/12 = 5/6. You cannot divide by a fraction equal to zero.'],
        ['How do you simplify a fraction?', 'Divide the numerator and denominator by their greatest common divisor (GCD). For 24/36 the GCD is 12, so 24/36 = 2/3.'],
        ['How do you convert a fraction to a decimal?', 'Divide the numerator by the denominator: 3/8 = 0.375. If the denominator has a prime factor other than 2 or 5, the decimal repeats, like 1/3 = 0.333…'],
        ['How do you convert a decimal to a fraction?', 'Write the digits over 10, 100, 1000 … according to the number of decimal places, then simplify: 0.75 = 75/100 = 3/4.'],
        ['How do you convert a fraction to a percentage?', 'Multiply the fraction by 100: 3/4 × 100 = 75%, and 1/8 × 100 = 12.5%.'],
        ['How do you compare two fractions?', 'Cross-multiply. For 2/3 and 3/5: 2 × 5 = 10 and 3 × 3 = 9; 10 is larger, so 2/3 > 3/5. This avoids rounding errors from decimals.'],
        ['How do you turn an improper fraction into a mixed number?', 'Divide the numerator by the denominator. The quotient is the whole number and the remainder goes over the denominator: 7/3 = 2 remainder 1 = 2 1/3.'],
        ['How do you find the least common denominator?', 'The least common denominator is the least common multiple (LCM) of the denominators. For 4 and 6 the multiples of 6 are 6, 12, …; 12 is the first one 4 divides, so the LCD is 12.'],
    ],
];
